#!/usr/bin/env python3
"""Register a CloudLab cluster: hostnames in, nodes.sh + config.json out.

After instantiating an experiment in the CloudLab UI (any node count), grab the
public hostnames from the List View (node-0 first — it becomes the control
plane) and run:

    python3 register_cluster.py apt120.apt.emulab.net apt096.apt.emulab.net ...

Rewrites, next to this script:
    nodes.sh      the NODES array sourced by bootstrap.sh / deploy.sh
    config.json   internal IPs (ip-base + i), nodes_user, nodes_home; the
                  enable_* feature gates of the existing file are preserved

Options: --user (default: existing nodes_user), --ip-base 10.0.0.101,
--home (default /users/<user>), --check (ssh-probe every host first).
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent


def bump_ip(base: str, i: int) -> str:
    parts = base.split(".")
    if len(parts) != 4 or not all(p.isdigit() for p in parts):
        sys.exit(f"[register_cluster] bad --ip-base: {base}")
    last = int(parts[3]) + i
    if last > 254:
        sys.exit(f"[register_cluster] ip range overflow: {base} + {i}")
    return ".".join(parts[:3] + [str(last)])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("hosts", nargs="+",
                    help="public hostnames, node-0 (control plane) first")
    ap.add_argument("--user", help="ssh user on the nodes (default: keep current)")
    ap.add_argument("--ip-base", default="10.0.0.101",
                    help="internal IP of node-0; node-i gets base+i (default %(default)s)")
    ap.add_argument("--home", help="home dir on the nodes (default /users/<user>)")
    ap.add_argument("--check", action="store_true",
                    help="ssh-probe every host before writing anything")
    args = ap.parse_args()

    cfg_path = SCRIPT_DIR / "config.json"
    old = {}
    if cfg_path.exists():
        with open(cfg_path) as f:
            old = json.load(f)

    user = args.user or old.get("nodes_user") or "yuhang"
    home = args.home or f"/users/{user}"
    ips = [bump_ip(args.ip_base, i) for i in range(len(args.hosts))]

    if args.check:
        bad = []
        for host in args.hosts:
            rc = subprocess.run(
                ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10",
                 "-o", "StrictHostKeyChecking=accept-new",
                 f"{user}@{host}", "true"]).returncode
            print(f"  {'ok  ' if rc == 0 else 'FAIL'} {user}@{host}")
            if rc != 0:
                bad.append(host)
        if bad:
            sys.exit(f"[register_cluster] unreachable: {', '.join(bad)} "
                     "(is the key in your ssh-agent?)")

    lines = [
        "# CloudLab node public hostnames — sourced by bootstrap.sh and deploy.sh.",
        "# (Not meant to be executed directly; it only defines the NODES array.)",
        "#",
        "# GENERATED by register_cluster.py — re-run it each time you swap",
        "# CloudLab experiments instead of editing by hand. node-0 is first and",
        f"# lines up with the internal-IP order in config.json ({ips[0]} == node-0).",
        "NODES=(",
    ]
    for i, (host, ip) in enumerate(zip(args.hosts, ips)):
        role = "  (control-plane)" if i == 0 else ""
        lines.append(f'\t"{host}"   # node-{i} / {ip}{role}')
    lines.append(")")
    (SCRIPT_DIR / "nodes.sh").write_text("\n".join(lines) + "\n")

    cfg = {
        "nodes_user": user,
        "nodes": ips,
        "nodes_home": home,
        # Preserve the add-on gates; default both on for new files.
        "enable_istio_metrics": old.get("enable_istio_metrics", True),
        "enable_audit_log": old.get("enable_audit_log", True),
    }
    with open(cfg_path, "w") as f:
        json.dump(cfg, f, indent=4)
        f.write("\n")

    workers = len(args.hosts) - 1
    print(f"[register_cluster] wrote nodes.sh + config.json: "
          f"{len(args.hosts)} nodes ({workers} workers), user={user}")
    for i, (host, ip) in enumerate(zip(args.hosts, ips)):
        print(f"  node-{i}  {ip:<12}  {host}"
              + ("  <- control plane" if i == 0 else ""))
    if workers < 1:
        print("[register_cluster] WARN: no workers — you need at least 2 nodes")
    print("Next: ./bootstrap.sh  (then deploy.sh; experiments can use up to "
          f"workers: {max(workers, 0)})")


if __name__ == "__main__":
    main()
